ES Module版本模板更新
Gary50613/Taiwan_COVID-19_RSS pull request #5
Opened 2021-10-29 15:33 UTC by Kayxue

今天要用Node.js 17.0.1執行時，偶然發現因為node-fetch已經變成ES Module而造成專案無法正常執行

所以我才改出這個版本，希望您會喜歡（已測試可以正常運行）

2021-10-29 15:54 UTC, kane50613 requested changes
從config.js移除token

2021-10-29 15:54 UTC, kane50613 commented on config.js
> +    "token": "Nzg0MDA2NTA5NDQ5MzE0MzA0.X8jA9Q.aHPJTIvVqJuEWZ5yZ47BcQ5zIAA",
欸不是 大哥你的token#

2021-10-29 15:59 UTC, kane50613 commented
對惹 這樣的話 [README.md#L37](https://github.com/Gary50613/Taiwan_COVID-19_RSS/blob/d3d4db6ae5e3d8a1bdf38b4d1cb089590dc6fbcb/README.md?plain=1#L37) 需要修改成 `config.js`

2021-10-29 16:04 UTC, Kayxue commented on config.js
> +    "token": "Nzg0MDA2NTA5NDQ5MzE0MzA0.X8jA9Q.aHPJTIvVqJuEWZ5yZ47BcQ5zIAA",
已重新生成新token

2021-10-30 01:43 UTC, Kayxue reviewed
viewed

2021-10-30 01:46 UTC, Kayxue commented
恩我先關好了
我整個專案重推
因為目前要推入的分支已經被github固定
你按接受的話一定推入main覆蓋原來的東西
所以我先關好了

2021-10-30 01:46 UTC, closed without merging